### ISSUE TITLE
Placeholder breaks if you reload PAPI.

### ISSUE THREAD

**Issue by mibby** [SaitDev/MobArenaExtension#2]
Would it be possible to add a reload command to re-initialize the placeholder? If you reload PAPI, you see ``{mobarena_arena_prefix}`` in chat.

**Comment by SaitDev** [comment]
Reload command is planned. It should exist for real production use

**Comment by SaitDev** [comment]
The bug with papi after being reloaded you reported is fixed on build 20. Let me know is solve your problem. For reload command lets create another issue for tracking it :)
