### ISSUE TITLE
Artifacts older than 1 month are automatically deleted.

### ISSUE THREAD

**Issue by TomLewis** [SaitDev/MobArenaExtension#22]
Hello!

Is there any chance to get download links fixed? Both the [Appveyor](https://ci.appveyor.com/project/SaitDev/mobarenaextension/build/artifacts) and [Github Action](https://github.com/SaitDev/MobArenaExtension/actions). have expired/deleted.

Maybe upload a version to the Github releases or create a spigot page to track for updates?

Thanks.

**Comment by LeRougeaud** [comment]
No. 🤣

**Comment by TomLewis** [comment]
You're not a contributor to this project?

**Comment by SaitDev** [comment]
@TomLewis sorry for the expired link, i can provide latest test build asap via these CI but the time limitation is kinda annoying . Thank for the suggestion, i may upload to spigot resource in the next couple of weeks after update extension to support newer version since i have some spare time now

**Comment by SaitDev** [comment]
Beside github action, you can now download from spigot https://www.spigotmc.org/resources/mobarenaextension.106125/

**Comment by TomLewis** [comment]
@SaitDev fantastic, thank you! I have now "watched" on Spigot, so I will get notificaitons for updates with the rest of the plugins! Thank you!
