### ISSUE TITLE
Does not work in 1.14.4

### ISSUE THREAD

**Issue by tacocoma** [SaitDev/MobArenaExtension#5]
I haven't tested this on any other version yet but I was told this add-on doesn't have 1.14 support. I'd be happy to pay for this update/fix to happen. Desperately need it on my server :)

**Comment by SaitDev** [comment]
What are features that not working on 1.14. I've seen people using on 1.15 also without reporting about not compatible

**Comment by SaitDev** [comment]
latest version drop support for MC 1.16. pls update to mobarena 0.107 and MC 1.18
