### ISSUE TITLE
Extension not casting to MobArena

### ISSUE THREAD

**Issue by gloamingwildwoods** [SaitDev/MobArenaExtension#6]
Here's a paste of the error report: https://pastebin.com/6eGFQSEx
Running build 298 of paper.

**Comment by SaitDev** [comment]
what is the version of mobarena. also i assume u mean paper 1.15.2 build 298

**Comment by gloamingwildwoods** [comment]
MobArena version is 0.104.2, and that's the build for paper. Apologies for the poor formatting.

**Comment by SaitDev** [comment]
As our conversation on discord, its loading order bug on paper which they fixed it later
