### ISSUE TITLE
Placeholders not working

### ISSUE THREAD

**Issue by B1022** [SaitDev/MobArenaExtension#7]
Hey Sait! Recently all my placeholders have not been working except for {mob_arena_wave} on my featherboard. Any ideas?
![image](https://user-images.githubusercontent.com/64097512/83975353-7f881280-a8c1-11ea-96c9-9e18d709a5a1.png)

**Comment by Chew** [comment]
1) Make sure you have PlaceholderAPI Installed
2) Add `placeholderapi_` before each phrase, e.g. {placeholderapi_mobarena_arena_mobs} instead of {mobarena_arena_mobs}
3) You misspelled "dealt" and "received"
