### ISSUE TITLE
1.15 Mob reversion

### ISSUE THREAD

**Issue by MooshroomStatus** [SaitDev/MobArenaExtension#8]
I'm using the latest version of Mob Arena and the Addon, running MC Paper 1.15.2, and I have this issue where my Mythic Mobs, at random and with no forewarning, will revert back into vanilla versions of their respective entities. My zombie boss (The Fire Revenant) will lose all his abilities and just become a vanilla diguised zombie, and my hell hounds will lose all their abilities and revert into vanilla angry wolves.)

I haven't seen anything in console about this. I'm not even sure if it's an issue with MA or the Addon, but I'm reporting it to both just in case. There's no trigger that causes this, no chunk unloading, plugin reloading or anything. It just happens mid-combat at random.

**Comment by SaitDev** [comment]
your boss and wolves are spawned due to wave monster config of mob arena or are summoned by other mythic mobs

**Comment by SaitDev** [comment]
No longer support 1.15
